name: Deploy to EC2 on Push to Main

on:
  push:
    branches:
      - main # Trigger only on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Check out the repository code

      - name: Set up SSH
        run: |
          # Start the SSH agent
          eval "$(ssh-agent -s)"

          # Add the private key to the agent
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" | ssh-add -

          # Provide the passphrase
          echo "$EC2_SSH_PASSPHRASE" | ssh-add - <<< $EC2_SSH_PASSPHRASE
        env:
          EC2_SSH_PASSPHRASE: ${{ secrets.EC2_SSH_PASSPHRASE }}

      - name: Copy project files to EC2
        run: |
          # Install rsync (for copying files)
          sudo apt-get install -y rsync

          # Sync files from GitHub to EC2
          rsync -avz --exclude '.git*' ./ ubuntu@${{ secrets.EC2_IP }}:/home/ubuntu/ecommerce/
        env:
          EC2_IP: ${{ secrets.EC2_IP }}

      - name: SSH into EC2 and restart Gunicorn
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP }} << 'EOF'
            cd /home/ubuntu/ecommerce
            git pull origin main 
            source venv/bin/activate 
            pip install -r requirements.txt 
            sudo systemctl restart gunicorn  
          EOF
        env:
          EC2_IP: ${{ secrets.EC2_IP }}
