name: Deployment on Production

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3 
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      - name: Copy project files to EC2
        run: |
          # Install rsync (for copying files)
          sudo apt-get install -y rsync

          # Sync files from GitHub to EC2
          rsync -avz --exclude '.git*' ./ ubuntu@3.126.55.131:/home/ubuntu/ecommerce/
        env:
          YOUR_EC2_IP: ${{ secrets.EC2_IP }}

      - name: SSH into EC2 and restart Gunicorn
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP }} << 'EOF'
            cd /home/ubuntu/ecommerce
            git pull origin main  
            source venv/bin/activate  
            pip install -r requirements.txt  
            sudo systemctl restart gunicorn 
          EOF
        env:
          EC2_SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          YOUR_EC2_IP: ${{ secrets.EC2_IP }}
